name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  autopep8:
    name: AutoPep8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install autopep8
    - run: autopep8 --in-place --aggressive --aggressive hw2/hw2_debugging.py hw2/rand.py

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install pylint
    - run: pylint hw2/hw2_debugging.py hw2/rand.py

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install mypy
    - run: mypy hw2/hw2_debugging.py hw2/rand.py

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install pytest coverage codecov
    - run: pytest hw2/test_merge_sort.py
    - run: coverage run -m pytest
    - run: coverage report
    - run: coverage html
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}