name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage codecov pre-commit pylint flake8 mypy autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive hw2/hw2_debugging.py

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Run pylint
      run: pylint hw2/hw2_debugging.py

    - name: Run flake8
      run: flake8 hw2/hw2_debugging.py

    - name: Run mypy
      run: mypy hw2/hw2_debugging.py

    - name: Run tests
      run: |
        coverage run -m pytest
        coverage report
        coverage html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.5cdedf67-5cd5-481e-b5f2-4a7b92c52060 }}
